const employees = [
  {
    empId: 1,
    name: "Teja",
    email: "teja@ind.com",
    password: "12345",
    newTasks: 0,
    completedTasks: 1,
    failedTasks: 1,
    activeTasks: 1,
    totalTasks: 3,
    tasks: [
      {
        taskId: "1_0",
        title: "Update Login UI",
        description: "Enhance the login form for better UX",
        date: "2025-04-05",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: "1_1",
        title: "Backend Auth Flow",
        description: "Implement secure auth flow in Node.js",
        date: "2025-04-03",
        category: "Backend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: "1_2",
        title: "Monitor Server Errors",
        description: "Add logging with proper alerts",
        date: "2025-04-01",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    empId: 2,
    name: "Arjun",
    email: "arjun@ind.com",
    password: "123456",
    newTasks: 1,
    completedTasks: 1,
    failedTasks: 0,
    activeTasks: 2,
    totalTasks: 4,
    tasks: [
      {
        taskId: "2_0",
        title: "Build User API",
        description: "Develop REST APIs for user module",
        date: "2025-04-02",
        category: "Backend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: "2_1",
        title: "Google Sign-in Setup",
        description: "Enable Google auth via Firebase",
        date: "2025-04-04",
        category: "Auth",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: "2_2",
        title: "Project Bootstrap",
        description: "Setup the React + Vite base project",
        date: "2025-03-30",
        category: "Setup",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: "2_3",
        title: "Fix API CORS",
        description: "Resolve cross-origin issues in Express",
        date: "2025-04-06",
        category: "Backend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    empId: 3,
    name: "Sneha",
    email: "sneha@ind.com",
    password: "1234567",
    newTasks: 1,
    completedTasks: 1,
    failedTasks: 0,
    activeTasks: 1,
    totalTasks: 3,
    tasks: [
      {
        taskId: "3_0",
        title: "Design Dashboard",
        description: "Create layout for the dashboard",
        date: "2025-03-31",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: "3_1",
        title: "Reusable Navbar",
        description: "Develop shared navbar component",
        date: "2025-04-01",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: "3_2",
        title: "Dark Mode Switch",
        description: "Toggle light/dark themes in app",
        date: "2025-04-02",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    empId: 4,
    name: "Vikram",
    email: "vikram@ind.com",
    password: "12345678",
    newTasks: 1,
    completedTasks: 0,
    failedTasks: 1,
    activeTasks: 1,
    totalTasks: 3,
    tasks: [
      {
        taskId: "4_0",
        title: "Setup Redux Toolkit",
        description: "Configure Redux with slices",
        date: "2025-04-03",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: "4_1",
        title: "Table Pagination",
        description: "Add pagination to employee list",
        date: "2025-04-05",
        category: "Frontend",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: "4_2",
        title: "Write Component Tests",
        description: "Test dashboard components with Jest",
        date: "2025-04-06",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    empId: 5,
    name: "Meera",
    email: "meera@ind.com",
    password: "123456789",
    newTasks: 1,
    completedTasks: 1,
    failedTasks: 0,
    activeTasks: 1,
    totalTasks: 3,
    tasks: [
      {
        taskId: "5_0",
        title: "Admin Dashboard Setup",
        description: "Build layout for admin panel",
        date: "2025-04-01",
        category: "Fullstack",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: "5_1",
        title: "Deploy with Docker",
        description: "Prepare Dockerfile for production",
        date: "2025-04-03",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: "5_2",
        title: "Image Optimization",
        description: "Improve loading speed with lazy loading",
        date: "2025-04-02",
        category: "Performance",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    name: "Ravi",
    email: "ravi.admin@ind.com",
    password: "adminpass1",
  },
  {
    id: 2,
    name: "Anjali",
    email: "anjali.admin@ind.com",
    password: "adminpass2",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
  // without this stringify method the data will be in object form so its necessary to convert
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  // we need to parse the string data into Json to access
  return { employees, admin };
};
